# Generated by Django 4.1.7 on 2023-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('photo_about', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('job', models.CharField(max_length=200)),
                ('profile_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='About_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('photo_team', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_one', models.TextField(blank=True)),
                ('description_two', models.TextField(blank=True)),
                ('description_three', models.TextField(blank=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('description_four', models.TextField(blank=True)),
                ('url_text', models.CharField(max_length=100)),
            ],
        ),
    ]
