# Generated by Django 4.1.7 on 2023-03-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='description_one',
        ),
        migrations.AddField(
            model_name='about',
            name='description_two',
            field=models.TextField(blank=True),
        ),
    ]
