# Generated by Django 4.1.7 on 2023-03-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_photos',
            new_name='ServicePhotos',
        ),
    ]
