# Generated by Django 4.1.7 on 2023-03-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_service_photos_servicephotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicePhotos',
            new_name='Service_photos',
        ),
    ]
